[project]
name = "dino-run-blink"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "matplotlib==3.8.2",
    "numpy==1.26.4",
    "pynput==1.7.6",
    "pylsl==1.16.2",
    "scipy==1.12.0"
]
